version: "3.8"

services:
  mlflow:
    build: .
    container_name: mlflow-server
    command: >
      mlflow ui
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlruns.db
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlruns.db

  simulation:
    build: .
    container_name: simulation-runner
    entrypoint: tail -f /dev/null  # idle container that does nothing
    depends_on:
      - mlflow
    volumes:
      - ./mlruns:/app/mlruns
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000