# Use the official Python image from the Docker Hub
FROM python:3.11

# Set the working directory in the container
WORKDIR /workspace

# Copy the rest of the working directory contents into the container at /workspace
COPY ../requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 for web applications (adjust if needed)

COPY ./ /workspace/

EXPOSE 8000

# Default command to run on container start
# CMD ["bash"]
